In [91]:
from datetime import datetime, timedelta, date
import csv
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('ggplot')
%matplotlib inline
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import roc_auc_score, recall_score, precision_score
#roc_auc_score(y_true, y_scores)

### Reading in the data & convert date to datetime object

In [2]:
file_name = '../Full_Monthly.csv'

In [3]:
def get_data(file):
    df = pd.read_csv(file, index_col = 0)
    df['Date'] = pd.to_datetime(df['Date'])
    return df

In [4]:
df = get_data(file_name)

In [5]:
df.head()

,Date,Ticker,Sector,Industry,Cash From Operations,Current Market Cap,EBITDA Margin,Free Cash Flow,Gross Margin,Interest Expense,...,Yield.10.Yr.Vol.63,Yield.20.Yr.Vol.21,Yield.20.Yr.Vol.63,Yield.30.Yr.Vol.21,Yield.30.Yr.Vol.63,Total,OAS,Shiller.PE.Ratio,VIX.Value,VIX.VXV
1,1998-07-01,BAX,"Consumer, Non-cyclical",Healthcare-Products,146.000,15118.3532,25.5814,17.000,46.0888,39.000,...,0.100107,0.067771,0.117695,0.06957,0.126968,76.83215,72.402903,38.26,24.799999,NaN
2,1998-07-01,VOD,Communications,Telecommunications,NaN,256921.1418,NaN,NaN,NaN,NaN,...,0.100107,0.067771,0.117695,0.06957,0.126968,76.83215,78.340585,38.26,24.799999,NaN
3,1998-07-01,PXD,Energy,Oil&Gas,91.369,2398.8883,45.2357,-56.929,23.5375,41.017,...,0.100107,0.067771,0.117695,0.06957,0.126968,76.83215,147.188061,38.26,24.799999,NaN
4,1998-07-01,KMI,Energy,Pipelines,453.000,36519.0472,27.3650,-10.000,34.1947,297.000,...,0.100107,0.067771,0.117695,0.06957,0.126968,76.83215,113.533557,38.26,24.799999,NaN
5,1998-07-01,AZN,"Consumer, Non-cyclical",Pharmaceuticals,311.000,82119.0000,28.0482,-203.000,69.4947,33.000,...,0.100107,0.067771,0.117695,0.06957,0.126968,76.83215,60.176544,38.26,24.799999,NaN

### To stay consistent, the tickers will we focus on are RTN, DE, and PG

In [5]:
df_pg = df[df.Ticker == 'PG']
df_pg.head()

,Date,Ticker,Sector,Industry,Cash From Operations,Current Market Cap,EBITDA Margin,Free Cash Flow,Gross Margin,Interest Expense,...,Yield.10.Yr.Vol.63,Yield.20.Yr.Vol.21,Yield.20.Yr.Vol.63,Yield.30.Yr.Vol.21,Yield.30.Yr.Vol.63,Total,OAS,Shiller.PE.Ratio,VIX.Value,VIX.VXV
95,1998-07-01,PG,"Consumer, Non-cyclical",Cosmetics/Personal Care,1585.000000,122142.135700,16.567900,688.000000,42.804800,152.000000,...,0.100107,0.067771,0.117695,0.069570,0.126968,76.832150,52.293873,38.26,24.799999,NaN
205,1998-08-01,PG,"Consumer, Non-cyclical",Cosmetics/Personal Care,1483.840889,108794.405880,19.692273,796.989102,43.908357,153.224175,...,0.096231,0.055283,0.115589,0.055848,0.125602,83.081350,56.404484,35.42,44.279999,NaN
327,1998-09-01,PG,"Consumer, Non-cyclical",Cosmetics/Personal Care,1361.314649,98696.973968,22.301042,841.120122,44.857757,154.763327,...,0.102958,0.085732,0.091965,0.108142,0.104934,117.118731,81.900132,33.53,40.950001,NaN
462,1998-10-01,PG,"Consumer, Non-cyclical",Cosmetics/Personal Care,1196.054153,95100.137871,23.878604,755.534982,45.498844,156.932432,...,0.313982,0.078516,0.187200,0.092554,0.218705,108.267015,76.465481,33.77,28.049999,NaN
541,1998-11-01,PG,"Consumer, Non-cyclical",Cosmetics/Personal Care,986.337246,100017.218606,24.109228,511.630336,45.756897,159.888808,...,0.374456,0.168363,0.194161,0.134962,0.247209,137.672554,78.197225,37.37,26.010000,NaN

In [23]:
def add_oas_columns(df):
    """Takes a dataframe indexed by date and adds 3 additional columns related to OAS"""
    df['oas_pct_change'] = df.OAS.pct_change()
    df = df.drop(df.index[0]) #drop the first row since pct change makes first value NaN
    df['outlier'] = np.where((df.oas_pct_change > np.mean(df.oas_pct_change) + np.std(df.oas_pct_change))|(df.oas_pct_change < np.mean(df.oas_pct_change) - np.std(df.oas_pct_change)),1,0)
    #df['oas_rank'] = pd.cut(df.oas_pct_change, bins = num_of_bins,labels = list(range(num_of_bins)))
    #df['outlier'] = np.where((df.oas_rank == 0)|(df.oas_rank == num_of_bins-1),1,0)
    return df

In [24]:
df_PG = add_oas_columns(df_pg)
df_PG.head()

/Users/veronicahsieh/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,Date,Ticker,Sector,Industry,Cash From Operations,Current Market Cap,EBITDA Margin,Free Cash Flow,Gross Margin,Interest Expense,...,Yield.20.Yr.Vol.63,Yield.30.Yr.Vol.21,Yield.30.Yr.Vol.63,Total,OAS,Shiller.PE.Ratio,VIX.Value,VIX.VXV,oas_pct_change,outlier
205,1998-08-01,PG,"Consumer, Non-cyclical",Cosmetics/Personal Care,1483.840889,108794.405880,19.692273,796.989102,43.908357,153.224175,...,0.115589,0.055848,0.125602,83.081350,56.404484,35.42,44.279999,NaN,0.078606,0
327,1998-09-01,PG,"Consumer, Non-cyclical",Cosmetics/Personal Care,1361.314649,98696.973968,22.301042,841.120122,44.857757,154.763327,...,0.091965,0.108142,0.104934,117.118731,81.900132,33.53,40.950001,NaN,0.452015,1
462,1998-10-01,PG,"Consumer, Non-cyclical",Cosmetics/Personal Care,1196.054153,95100.137871,23.878604,755.534982,45.498844,156.932432,...,0.187200,0.092554,0.218705,108.267015,76.465481,33.77,28.049999,NaN,-0.066357,0
541,1998-11-01,PG,"Consumer, Non-cyclical",Cosmetics/Personal Care,986.337246,100017.218606,24.109228,511.630336,45.756897,159.888808,...,0.194161,0.134962,0.247209,137.672554,78.197225,37.37,26.010000,NaN,0.022647,0
634,1998-12-01,PG,"Consumer, Non-cyclical",Cosmetics/Personal Care,815.392254,110112.495792,23.541495,237.578677,45.900699,163.108011,...,0.132408,0.072005,0.146521,117.358650,76.643962,38.82,24.420000,NaN,-0.019863,0

In [27]:
features = ['Date','Current Market Cap','Shares.Outstanding','Gross Margin','Interest Expense','Cash From Operations','EBITDA Margin','Net Debt','Total Current Liabilities','Total Assets','Revenue','Long Term Debt','Stock.Price','Net Income/Net Profit (Losses)','Short and Long Term Debt','Free Cash Flow']

In [28]:
def create_model_data(features_list,df):
    """Lags all the features by 1 month and merges it back to the outlier column"""
    df_features = df[features]
    df_features['Date'] = df_features['Date'] + pd.DateOffset(months=1)
    df_y = df[['Date','outlier']]
    df_lagged = pd.merge(df_features,df_y,on = 'Date')
    return df_lagged

In [30]:
model_data = create_model_data(features,df_PG)
model_data.head()

/Users/veronicahsieh/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.

,Date,Current Market Cap,Shares.Outstanding,Gross Margin,Interest Expense,Cash From Operations,EBITDA Margin,Net Debt,Total Current Liabilities,Total Assets,Revenue,Long Term Debt,Stock.Price,Net Income/Net Profit (Losses),Short and Long Term Debt,Free Cash Flow,outlier
0,1998-09-01,108794.405880,2682.6,43.908357,153.224175,1483.840889,19.692273,5888.137838,9757.182639,31720.566855,9310.013242,6003.047478,38.25000,888.544664,8729.007668,796.989102,1
1,1998-10-01,98696.973968,2682.6,44.857757,154.763327,1361.314649,22.301042,6117.348401,10188.100241,32382.683650,9375.383492,6209.170005,35.56250,1059.025956,9294.899648,841.120122,0
2,1998-11-01,95100.137871,2674.8,45.498844,156.932432,1196.054153,23.878604,6308.704413,10466.487770,32859.900323,9505.467760,6351.442634,44.34375,1165.380505,9626.560254,755.534982,0
3,1998-12-01,100017.218606,2674.8,45.756897,159.888808,986.337246,24.109228,6447.128215,10541.330812,33091.135604,9709.092595,6409.598679,43.81250,1188.298315,9653.631664,511.630336,0
4,1999-01-01,110112.495792,2651.8,45.900699,163.108011,815.392254,23.541495,6534.188979,10470.805869,33150.955837,9893.332120,6413.785136,45.65625,1163.618627,9507.950427,237.578677,0

In [98]:
test = model_data.iloc[176:232]

In [99]:
train = model_data.iloc[0:175]
train

,Date,Current Market Cap,Shares.Outstanding,Gross Margin,Interest Expense,Cash From Operations,EBITDA Margin,Net Debt,Total Current Liabilities,Total Assets,Revenue,Long Term Debt,Stock.Price,Net Income/Net Profit (Losses),Short and Long Term Debt,Free Cash Flow,outlier
0,1998-09-01,108794.405880,2682.600,43.908357,153.224175,1483.840889,19.692273,5888.137838,9757.182639,31720.566855,9310.013242,6003.047478,38.250000,888.544664,8729.007668,796.989102,1
1,1998-10-01,98696.973968,2682.600,44.857757,154.763327,1361.314649,22.301042,6117.348401,10188.100241,32382.683650,9375.383492,6209.170005,35.562500,1059.025956,9294.899648,841.120122,0
2,1998-11-01,95100.137871,2674.800,45.498844,156.932432,1196.054153,23.878604,6308.704413,10466.487770,32859.900323,9505.467760,6351.442634,44.343750,1165.380505,9626.560254,755.534982,0
3,1998-12-01,100017.218606,2674.800,45.756897,159.888808,986.337246,24.109228,6447.128215,10541.330812,33091.135604,9709.092595,6409.598679,43.812500,1188.298315,9653.631664,511.630336,0
4,1999-01-01,110112.495792,2651.800,45.900699,163.108011,815.392254,23.541495,6534.188979,10470.805869,33150.955837,9893.332120,6413.785136,45.656250,1163.618627,9507.950427,237.578677,0
5,1999-02-01,120604.706490,2651.800,46.291863,165.881357,789.404799,22.957560,6575.954572,10342.597555,33150.585222,9937.762546,6407.772956,45.437500,1142.084394,9375.994763,103.920113,0
6,1999-03-01,127490.764539,2651.800,47.108023,167.620366,980.574408,22.929397,6575.826523,10232.322503,33168.028179,9762.343036,6423.424528,44.750000,1156.153465,9396.517373,233.613185,0
7,1999-04-01,130406.225034,2652.800,47.666579,168.298618,1302.189624,23.046230,6524.738990,10159.168685,33125.960176,9475.853945,6436.920172,48.968750,1152.786658,9485.115966,527.135435,0
8,1999-05-01,130049.240052,2652.800,47.033715,168.053832,1621.132016,22.610283,6409.985271,10125.845144,32901.695776,9242.217318,6408.179306,46.906250,1053.976984,9492.220017,819.993002,0
9,1999-06-01,127200.242091,2657.000,44.638554,166.913181,1825.934707,21.165510,6249.144463,10147.949348,32440.373761,9191.976110,6314.530752,46.687500,813.401390,9325.026080,978.263002,0
10,1999-07-01,123055.152380,2657.000,41.745956,164.344640,1914.662639,19.478569,6212.969450,10306.272501,32030.184054,9286.823691,6221.361934,44.062500,544.994717,9177.871996,1022.675983,0
11,1999-08-01,118940.937824,2657.000,40.199771,159.639811,1919.927225,18.701767,6520.524321,10702.167998,32067.515346,9435.198056,6221.834074,45.281250,413.237351,9335.660342,1022.740385,0
12,1999-09-01,116257.280395,2657.000,41.404469,152.706302,1863.691313,19.700690,7326.775075,11387.084952,32841.441028,9563.321857,6392.337038,49.625000,542.245589,10010.057296,1026.124073,0
13,1999-10-01,116801.597911,2657.000,44.358362,146.823797,1709.561077,21.770768,8435.745606,12139.277916,34053.418184,9694.872654,6717.404862,46.875000,835.097493,11011.680742,960.849104,0
14,1999-11-01,122506.698309,2639.508,47.240696,146.419838,1401.277961,23.672946,9531.998380,12644.005442,35204.878079,9886.701862,7150.303661,52.437500,1119.629247,12014.630891,714.209853,0
15,1999-12-01,134069.431321,2639.508,48.518197,154.663220,915.253204,24.360523,10344.123604,12647.672583,35872.692821,10173.328924,7644.425759,54.000000,1249.863545,12739.679414,218.976568,0
16,2000-01-01,144859.178360,2631.400,48.365814,167.255128,421.664077,23.929716,10862.301629,12259.623825,36081.941959,10456.724170,8154.066674,54.781250,1235.430605,13184.944771,-322.296218,0
17,2000-02-01,145555.453816,2631.400,47.585573,177.155441,161.818127,22.896302,11172.740882,11722.436406,36022.239144,10590.199996,8633.853483,50.531250,1143.083176,13450.357662,-608.017881,0
18,2000-03-01,129030.737495,2631.400,46.880486,178.843914,328.124091,21.714646,11351.640791,11252.450156,35862.264738,10458.518201,9037.405509,43.937500,1032.149919,13618.886792,-398.917652,0
19,2000-04-01,102276.296481,2631.400,46.311100,176.594230,798.060051,20.440360,11409.938365,10896.090608,35634.562682,10149.017662,9311.862804,28.375000,913.690148,13663.500497,142.824616,1
20,2000-05-01,77868.045019,2631.400,45.683840,178.554033,1324.534141,18.971329,11332.756244,10632.574164,35317.828534,9829.166058,9401.802566,29.875000,779.670372,13513.656772,696.236390,0
21,2000-06-01,66642.770452,2615.800,44.862081,191.065568,1685.181984,17.289641,11115.634083,10438.906631,34905.335778,9646.138499,9273.942394,33.250000,629.243197,13123.080889,980.391710,0
22,2000-07-01,67212.287867,2615.800,44.110765,207.813446,1832.237660,15.967340,10827.204778,10277.837525,34492.953064,9604.207688,9049.449885,28.375000,512.006231,12615.487715,996.388212,0
23,2000-08-01,72982.459375,2615.800,43.865834,217.092079,1792.287268,15.827697,10567.227676,10106.045380,34220.238758,9646.791942,8915.264521,28.500000,499.038870,12186.981469,865.422096,0
24,2000-09-01,78044.197655,2615.800,44.474340,209.384283,1598.961348,17.507864,10424.325276,9896.094341,34211.659071,9722.187466,9030.145672,30.914049,645.965614,12015.507612,701.335346,0
25,2000-10-01,81825.771694,2615.800,45.604881,191.908365,1337.193776,20.227441,10401.849173,9741.105748,34476.082686,9817.361103,9337.451318,33.500000,890.686327,12139.370489,558.873785,0
26,2000-11-01,86200.410254,2612.271,46.615263,179.548898,1115.419690,22.556675,10464.089695,9789.426315,34969.424860,9936.994109,9681.867419,35.718750,1117.173053,12532.907029,465.712201,0
27,2000-12-01,92643.793509,2612.271,46.951959,185.079800,1029.084349,23.248425,10574.582033,10155.451909,35634.304658,10079.805499,9922.107888,37.437500,1223.420023,13153.372236,444.847115,0
28,2001-01-01,99247.846848,2607.600,46.806071,203.537884,1065.486576,22.589557,10692.307825,10671.188417,36305.946153,10194.578994,10036.817863,39.218750,1225.386797,13819.874109,481.849912,0
29,2001-02-01,102438.432790,2607.600,46.735332,221.226725,1158.677019,21.622236,10774.006671,11029.601072,36766.695235,10205.511621,10063.693140,35.919998,1197.115648,14283.501059,543.864926,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,2010-10-01,170310.055139,2837.458,49.810484,209.543375,2916.864564,20.663748,27923.588903,25081.553630,128916.884928,19123.837446,21222.301959,59.970001,2382.784563,30472.534353,1924.726114,0
146,2010-11-01,168769.911171,2837.458,50.718850,207.944765,2600.625803,23.145363,29253.521052,26349.677427,131037.857908,19484.917309,21289.413540,63.570000,2702.673482,31679.329131,1839.772021,0
147,2010-12-01,169511.830105,2799.193,51.660008,207.831846,2465.649507,25.430182,30227.126344,27435.433618,133246.738503,19967.801350,21438.318943,61.070000,3010.333503,32772.255113,1913.877883,0
148,2011-01-01,172751.516867,2799.193,52.126769,208.709694,2453.855087,25.980241,30457.728584,27927.984017,134364.594922,20566.100094,21469.458241,64.330002,3227.496685,33239.828821,1950.836247,0
149,2011-02-01,177004.265420,2799.193,52.111707,209.641996,2554.338983,24.990512,30056.989922,27836.810906,134456.815335,21115.944900,21389.594662,63.130001,3335.050769,33093.246830,1961.454197,0
150,2011-03-01,179853.695794,2800.784,51.881221,209.450594,2782.046447,23.605459,29409.617590,27401.694790,134270.564550,21367.182550,21318.538166,63.049999,3346.295547,32630.087887,2069.964371,0
151,2011-04-01,179175.684667,2800.784,51.677011,207.158121,3144.820581,22.870631,28878.782308,26859.831806,134501.057608,21106.624514,21364.930949,61.599998,3274.959331,32135.567230,2383.231881,0
152,2011-05-01,175947.659953,2800.784,51.458108,203.876165,3574.795753,22.715081,28577.585387,26397.616907,135237.862903,20510.045679,21510.745956,64.900002,3135.762472,31737.696414,2817.698650,0
153,2011-06-01,172970.397183,2791.294,51.017372,201.944372,3959.598496,22.411496,28472.116718,26171.579915,136214.499774,19981.885711,21663.489506,67.000000,2944.008526,31472.069704,3177.860147,0
154,2011-07-01,172800.181688,2791.294,50.179832,203.452074,4189.927117,21.318876,28528.430405,26317.053734,137167.075435,19894.532032,21741.075968,63.570000,2719.371765,31373.329536,3280.742706,0
155,2011-08-01,174975.835096,2791.294,49.156933,207.491273,4197.503806,19.863314,28733.361834,26734.845152,137912.162209,20226.282521,21789.419962,61.490002,2530.688138,31478.711314,3100.691888,0
156,2011-09-01,177133.984417,2791.294,48.403716,211.264470,3939.912020,19.143593,29086.846806,27177.916826,138317.057235,20707.002904,21935.126843,63.680000,2477.784875,31827.085035,2711.226543,1
157,2011-10-01,177089.055809,2747.768,48.338318,212.165950,3391.075356,20.134133,29578.017858,27420.726901,138261.643634,21079.746545,22281.676976,63.180000,2645.095179,32442.859431,2192.270061,0
158,2011-11-01,175226.526886,2747.768,48.874559,210.331763,2722.311972,22.138476,30059.647915,27532.651518,137771.877507,21299.068670,22630.462202,63.990002,2920.359377,33170.993814,1683.859725,0
159,2011-12-01,173668.951421,2751.320,49.585527,207.750382,2238.305454,23.331274,30292.381438,27782.321876,136972.406057,21462.421230,22578.774689,64.570000,3058.426439,33735.206317,1366.647486,1
160,2012-01-01,174430.069975,2751.320,50.060879,206.273224,2221.847909,22.033810,30061.410415,28411.118912,135995.610595,21659.402642,21766.845442,66.709999,2833.763784,33880.699440,1406.439233,0
161,2012-02-01,177590.693101,2751.320,50.204161,205.403346,2622.401607,18.860632,29510.941001,29236.954104,135054.159211,21835.598999,20473.936024,63.040001,2322.995686,33677.327783,1755.795192,0
162,2012-03-01,181832.609769,2754.399,50.146109,202.944101,3148.170404,16.086112,29045.027645,29771.239000,134418.830188,21832.362745,19441.827355,67.620003,1821.442370,33429.923569,2212.932040,0
163,2012-04-01,185799.291350,2754.399,50.015005,196.870629,3517.344503,15.866141,29038.132202,29551.793183,134333.247834,21503.698378,19369.720409,67.209999,1614.798568,33422.435265,2581.502336,0
164,2012-05-01,188026.671674,2754.399,49.825416,188.328266,3680.439218,18.005761,29329.716193,28619.023289,134610.928805,20930.031192,20157.133228,63.639999,1769.497277,33543.857373,2799.382475,0
165,2012-06-01,186967.334382,2754.399,49.503773,180.919508,3768.040402,20.487912,29344.573102,27402.881114,134732.021934,20367.280700,21083.765630,62.290001,2182.026121,33377.063481,2908.483061,1
166,2012-07-01,181283.750782,2740.106,48.985993,178.086493,3905.945884,21.356931,28538.913842,26328.196584,134206.304936,20062.888951,21453.715706,61.250000,2741.405075,32531.558722,2950.733471,0
167,2012-08-01,173200.417510,2740.106,48.405975,179.499809,4060.526789,20.487784,27078.592346,25562.862081,133187.487571,20044.908052,21252.830773,64.540001,3285.781604,31198.480168,2922.735243,0
168,2012-09-01,167897.483853,2740.106,48.061902,181.700535,4065.867152,19.274439,25718.301225,25061.571573,132363.593447,20159.347475,21032.651464,67.190002,3611.090821,30051.584134,2783.478353,0
169,2012-10-01,170322.822360,2757.354,48.239780,181.293867,3765.340107,19.095902,25194.285376,24774.086424,132408.604415,20255.028235,21334.587791,69.360001,3527.826236,29747.373985,2497.456804,0
170,2012-11-01,179393.140845,2757.354,48.904101,177.862532,3251.506654,20.188893,25562.870642,24678.674268,133430.112270,20336.766552,22189.170515,69.239998,3143.335427,30345.099668,2153.680674,0
171,2012-12-01,188668.745943,2734.230,49.733817,173.633669,2838.236654,21.775634,26276.532802,24778.919744,135032.686171,20547.921190,23173.208043,69.830002,2828.608163,31373.578112,1951.745316,0
172,2013-01-01,191821.767399,2734.230,50.406989,170.839641,2831.924078,23.064011,26784.578612,25076.701756,136806.688977,21025.107118,23859.507608,67.889999,2944.914789,32354.032137,2084.011347,0
173,2013-02-01,188790.184948,2734.230,50.791622,169.889963,3220.036349,23.701817,26911.011661,25519.532767,138411.429204,21661.895232,24068.355571,75.160004,3456.488881,33035.685858,2509.905887,0
174,2013-03-01,185467.328083,2731.651,50.936256,169.461631,3686.918550,23.754957,26835.964503,26003.252889,139571.744467,22120.856254,23855.253749,76.180000,3950.202151,33384.466226,2967.465427,0

In [103]:
train_X = train[['Current Market Cap', 'Shares.Outstanding', 'Gross Margin',
       'Interest Expense', 'Cash From Operations', 'EBITDA Margin',
       'Net Debt', 'Total Current Liabilities', 'Total Assets', 'Revenue',
       'Long Term Debt', 'Stock.Price', 'Net Income/Net Profit (Losses)',
       'Short and Long Term Debt', 'Free Cash Flow']]

In [104]:
test_X = test[['Current Market Cap', 'Shares.Outstanding', 'Gross Margin',
       'Interest Expense', 'Cash From Operations', 'EBITDA Margin',
       'Net Debt', 'Total Current Liabilities', 'Total Assets', 'Revenue',
       'Long Term Debt', 'Stock.Price', 'Net Income/Net Profit (Losses)',
       'Short and Long Term Debt', 'Free Cash Flow']]

In [105]:
train_Y = train[['outlier']]

In [106]:
test_Y = test[['outlier']]

In [107]:
clf = LogisticRegression(random_state=0, solver='lbfgs',multi_class='multinomial').fit(train_X, train_Y)

/Users/veronicahsieh/miniconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [108]:
clf2 = LogisticRegressionCV(cv=10, random_state=0,multi_class='multinomial').fit(train_X, train_Y)

/Users/veronicahsieh/miniconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:526: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [109]:
predicted_Y = clf.predict(test_X)

In [110]:
predicted_Y2 = clf2.predict(test_X)

In [89]:
def performance_metrics(actual,predicted):
    """Calculates the AUC, precision, and recall scores for the test set using sklearn metrics"""
    auc = roc_auc_score(actual, predicted)
    precision = list(precision_score(actual, predicted, average=None))
    recall = list(recall_score(actual, predicted,average =None))
    print("auc: {}".format(auc))
    print("precision: {}".format(precision))
    print("recall: {}".format(recall))
    return auc, precision, recall

In [111]:
test1 = performance_metrics(test_Y,predicted_Y2)
test1

auc: 0.5
precision: [0.8928571428571429, 0.0]
recall: [1.0, 0.0]

/Users/veronicahsieh/miniconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

(0.5, [0.8928571428571429, 0.0], [1.0, 0.0])

In [114]:
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=4)
neigh.fit(train_X, train_Y)

/Users/veronicahsieh/miniconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=4, p=2,
           weights='uniform')

In [115]:
predicted_Y3 = neigh.predict(test_X)

In [117]:
neigh.score(train_X,train_Y)

0.9085714285714286

In [116]:
test3 = performance_metrics(test_Y,predicted_Y3)
test3

auc: 0.5
precision: [0.8928571428571429, 0.0]
recall: [1.0, 0.0]

/Users/veronicahsieh/miniconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

(0.5, [0.8928571428571429, 0.0], [1.0, 0.0])